# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Host-Write "ThisIsASecretAndShouldNotBeVisible"
      Host-Write "ThisIsASecretAndShouldNotBeVisible!"
      Host-Write "$(MYSECRET)"
      Host-Write $(MYSECRET).Substring(0, 1)
      $list = new-object System.Collections.Generic.Dictionary<string, string>
      $list.Add("1234567890123456789012", $(MYSECRET)); //[System.Net.HttpRequestHeader]::Authorization
    errorActionPreference: 'continue'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '[string]::Format("Test {0}", $(MYSECRET))'
    ignoreLASTEXITCODE: true